baseURL = 'https://Udollfusi.github.io/'
languageCode = 'en-us'
title = '6by9'
theme = 'hugo-coder'

sectionPagesMenu = 'main'

enableEmoji = true
enableRobotsTXT = true

[params]
  author = "Brian Winters"
  fediverseCreator = "@Udollfusi@techhub.social"
  since = 2024
  colorScheme = "dark"
  hidecolorschemetoggle = true

[[params.social]]
  name = "mastodon"
  icon = "fa-brands fa-mastodon fa-2x"
  url = "https://techhub.social/@Udollfusi"
[[params.social]]
  name = "github"
  icon = "fa-brands fa-github fa-2x"
  url = "https://github.com/Udollfusi"

[[menu.main]]
  name = "BG3"
  weight = 1
  url = "bg3/"
