baseURL = 'https://Udollfusi.github.io/'
languageCode = 'en-us'
title = '6by9'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
# Paginate = 3
#googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "near-black"
  author = " Brian Winters"
  site_logo = "favicons/favicon-32x32.png"
  #description = ""
  copyright = "copyright &copy; Brian Winters"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  recent_posts_number = 3
  enableGitInfo = true

[[params.ananke_socials]]
  name = "mastodon"
  url = "https://techhub.social/@Udollfusi"
  rel = "me noopener"
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/Udollfusi"
#[[params.ananke_socials]]
#  name = "twitter"
#  url = "https://twitter.com/bdwinters"
#[[params.ananke_socials]]
#  name = "facebook"
#  url = "https://facebook.com/"
#  follow = false
